export const LOAD_WEATHER_STARTED = 'LOAD_WEATHER_STARTED'
export const LOAD_FINISHED = 'LOAD_FINISHED';
export const LOAD_WEATHER_PROCESS = 'LOAD_WEATHER_PROCESS';

export const CITY_SEARCH_COMPLETED = 'CITY_SEARCH_COMPLETED';
export const CITY_SEARCH_STARTED = 'CITY_SEARCH_STARTED';

export const SET_CITY_ID = 'SET_CITY_ID';